### ISSUE TITLE
Be able to load config from config file and override with env vars

### ISSUE THREAD

**Issue by jcchavezs** [openfga/openfga-envoy#2]
Currently we can only load config from config file however, there are several situations it is more convenient to also load them from env vars e.g. https://github.com/openfga/openfga-envoy/pull/1/files#diff-ab4fe07ea2ef780130aa6da25ff29b4d97d746b6caabb4b1f392d275056288d3R4 using something like viper e.g. https://dev.to/techschoolguru/load-config-from-file-environment-variables-in-golang-with-viper-2j2d

**Comment by holgerson97** [comment]
Hi @jcchavezs,

I would like to work on that, is there already development ongoing?

**Comment by jcchavezs** [comment]
Hi @holgerson97, there is not ongoing on this. Feel free to pick it up.

**Comment by jcchavezs** [comment]
Hi @holgerson97, did you have the time to look into this?

**Comment by holgerson97** [comment]
@jcchavezs not yet, I will let you know asap when I've got time
